In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [3]:
df = pd.read_csv(r"C:\Users\abbas\VS Codes\TensorFlow\insurance_data.csv")
print(df.head(3)

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1


In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)


In [49]:
print(len(X_train))

22


In [50]:
#Scaling Since we know that age is from 1 to 100
#So we divide it by 100
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [51]:
X_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train_scaled, y_train, epochs=5000)

Epoch 1/5000


C:\Users\abbas\AppData\Local\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5000 - l

In [28]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))


In [29]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


In [42]:
class myNN:
    def _init_(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0
    def fit(self, X, y, epochs, loss_thresold):
       self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_thresold) #this will return values in a tuple so we have to store it in tuple

    def predict(self, X_test):
        weighted_sum = self.w1 * X_test['age'] + self.w2 * X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)
            
    def gradient_descent(self,age, affordability, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)

            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            if i%50 == 0: 
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
 
            if loss<=loss_thresold:
                break

        return w1, w2, bias

In [43]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=500, loss_thresold=0.4631)

Epoch:0, w1:0.9736899318847281, w2:0.931388810977659, bias:-0.11748951666770448, loss:0.7428288579142563
Epoch:50, w1:1.5242798722391318, w2:0.8822187836689881, bias:-1.1310088596841466, loss:0.5943161377198863
Epoch:100, w1:2.228187036337397, w2:1.0212075704807773, bias:-1.5219348336892933, loss:0.5674253359204207
Epoch:150, w1:2.878880202063386, w2:1.0918966282424583, bias:-1.8376731064036331, loss:0.5462065237139113
Epoch:200, w1:3.473286412049912, w2:1.1354958313845407, bias:-2.109494376761035, loss:0.5289749850551891
Epoch:250, w1:4.014235251285109, w2:1.168307211546194, bias:-2.3515205001257873, loss:0.5148317335261617
Epoch:300, w1:4.506491403088422, w2:1.1967920767703706, bias:-2.570834600613761, loss:0.5031414005690805
Epoch:350, w1:4.955154772161111, w2:1.2234470550440066, bias:-2.7714756232427904, loss:0.4934177492028928
Epoch:400, w1:5.3650419915514505, w2:1.2491715720776857, bias:-2.956078966702517, loss:0.48528128420193223
Epoch:450, w1:5.740481994774169, w2:1.27423488383

In [31]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,500, 0.4631)


Epoch:0, w1:0.9736899318847281, w2:0.931388810977659, bias:-0.11748951666770448, loss:0.7428288579142563
Epoch:1, w1:0.9536535852311093, w2:0.8740290167758512, bias:-0.21881533456146035, loss:0.7072146449948487
Epoch:2, w1:0.9393731039296968, w2:0.8271852202997496, bias:-0.3053620401943441, loss:0.6814881914786812
Epoch:3, w1:0.930193258899806, w2:0.7897792032048467, bias:-0.37884372361582785, loss:0.6633428084673968
Epoch:4, w1:0.9254091137248937, w2:0.7605726653866934, bias:-0.441082368200183, loss:0.650742850709519
Epoch:5, w1:0.9243325693598606, w2:0.738313053647322, bias:-0.4938425798625155, loss:0.6420508089402462
Epoch:6, w1:0.9263332963572349, w2:0.7218280753843739, bias:-0.5387319906498417, loss:0.6360356979531206
Epoch:7, w1:0.9308580975636879, w2:0.7100747303660235, bias:-0.5771558825717441, loss:0.631816485354411
Epoch:8, w1:0.9374354910317361, w2:0.7021560855322683, bias:-0.6103083840841516, loss:0.6287844495353144
Epoch:9, w1:0.9456716791005844, w2:0.6973185496313956, bia

(6.078664716830392, 1.298189069004503, -3.281439927751994)

In [21]:
model.evaluate(X_test_scaled,y_test) #for evaluating the model data it shows accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 575ms/step - accuracy: 1.0000 - loss: 0.2647


[0.26470300555229187, 1.0]

In [23]:
model.predict(X_test_scaled) #through this you compare that the person of age 47 has the probability to buy insurance or not. if it is greater than
# 0.5 then he will buy insurance. also example of 18 years of 
# age having probability < 0.5 then will not buy insurance.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step


array([[0.81626713],
       [0.7576754 ],
       [0.8236742 ],
       [0.18819511],
       [0.38559136],
       [0.1959822 ]], dtype=float32)

In [44]:
customModel.predict(X_test_scaled)

9     0.848738
25    0.785705
8     0.856377
21    0.154336
0     0.343904
12    0.162438
dtype: float64

In [24]:
y_test

9     1
25    1
8     1
21    0
0     0
12    0
Name: bought_insurance, dtype: int64

In [25]:
coef, intercept = model.get_weights()
coef, intercept #this will gives us w1, w2 and b. values, these are in array format

(array([[5.0183096],
        [1.1966311]], dtype=float32),
 array([-2.7665412], dtype=float32))