In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [4]:
daily_sales_numbers = [24,32,14,-2,7,19,28]

In [5]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(3)

for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1728 1008  504]
[2304 2016 1368]


In [6]:
images_ds = tf.data.Dataset.list_files('images/*/*', shuffle=False)

for file in images_ds.take(3):
    print(file.numpy())

b'images\\cats\\1440.jpg'
b'images\\cats\\2022-cute-cat-moments.jpg'
b'images\\cats\\3-17-5-27-1-5-13m.jpg'


In [8]:
images_ds = images_ds.shuffle(50) #take a example of buffer so basically it stores 200 images first then again other images

for file in images_ds.take(5):
    print(file.numpy())

b'images\\cats\\cute-white-kitten-1024x678.jpg'
b'images\\dogs\\e04c8c32-f536-41d9-919c-e04e41589157_can+dogs+eat+bread+_281_29.jpg'
b'images\\dogs\\Screen-Shot-2024-04-01-at-12.30.27-PM-768x597.jpg'
b'images\\dogs\\Can-Dogs-Eat-Bread (2).jpg'
b'images\\cats\\pexels-photo-4017827.jpeg_cs=srgb&dl=pexels-muaz-aj-1782491-4017827.jpg'


In [9]:
class_names = ["cat", "dog"]

In [10]:
image_count = len(images_ds)

image_count #So it means total 180 images we have in a folder

180

In [11]:
train_size = int(image_count*0.8) #So it means 80 percent data is for training

train_ds = images_ds.take(train_size) #it will take first 80 percent of data means images
test_ds = images_ds.skip(train_size) #it will skip those images which were taken by train_ds. So it means 


In [14]:
len(train_ds)

144

In [15]:
len(test_ds)

36

In [38]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path, os.path.sep)[-2]
        # return file_path.split("\\")[-2] this is not supported by tensorflow library so we use other way

In [34]:
def process_image(file_path):
    label = get_label(file_path)

    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128,128])

    return img, label

In [35]:
def scale(image, label):

        scaled_image = image/255
        return scaled_image, label
         

In [39]:
for t in train_ds.take(5):
    print(t.numpy())

AttributeError: 'tuple' object has no attribute 'numpy'

In [40]:
for label in train_ds.map(get_label):
    print(label) #this we done was for y label.Now we will do it for X label.

TypeError: in user code:


    TypeError: outer_factory.<locals>.inner_factory.<locals>.tf__get_label() takes 1 positional argument but 2 were given


In [28]:
train_ds = train_ds.map(process_image)
for img, label in train_ds.take(3):
        print("image: ", img)
        print("label: ", label)

image:  tf.Tensor(
[[[ 67.618164  85.453125  25.889648]
  [ 94.01367  102.68164   28.105469]
  [ 86.96387   79.88281   25.460938]
  ...
  [ 90.802734 100.13672   41.307617]
  [ 95.16211  101.231445  42.884766]
  [101.80957  111.25293   59.40918 ]]

 [[ 70.58984   89.8584    39.003906]
  [ 60.038086  82.6582    24.886719]
  [102.57031  101.89844   53.745117]
  ...
  [118.44238  122.677734  75.23047 ]
  [ 64.59863   89.96289   23.932617]
  [ 75.42871  105.00195   44.760742]]

 [[ 82.7832    98.069336  27.271484]
  [111.86328  117.40332   50.288086]
  [109.25781  122.03418   50.03418 ]
  ...
  [ 80.4082    89.836914  29.875977]
  [ 71.71973   78.981445  22.875   ]
  [ 65.85449   79.65234   23.805664]]

 ...

 [[ 57.655273  24.342773   5.      ]
  [116.83496   63.43457   54.512695]
  [141.05176   80.05176   78.72949 ]
  ...
  [ 71.63379   54.554688  29.499023]
  [ 68.05078   62.09375   37.154297]
  [ 58.85547   52.120117  33.745117]]

 [[ 68.65137   50.805664  15.133789]
  [132.80176   70.

InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Error in user-defined function passed to MapDataset:31 transformation with iterator: Iterator::Root::Prefetch::FiniteTake::ParallelMapV2: Unknown image file format. One of JPEG, PNG, GIF, BMP required.
	 [[{{node DecodeJpeg}}]] [Op:IteratorGetNext] name: 

In [33]:
trains_ds = train_ds.map(scale)

for image, label in train_ds.take(3):
    print("image: ", images.numpy()[0][0])
    print("label: ", label.numpy())

NameError: name 'images' is not defined